// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0f0NvkYbt2MddVG_oF_UNoJ_AxPRMeAU',
    appId: '1:951730653228:web:06558ebc1651157a5aa989',
    messagingSenderId: '951730653228',
    projectId: 'e-nudge',
    authDomain: 'e-nudge.firebaseapp.com',
    storageBucket: 'e-nudge.firebasestorage.app',
    measurementId: 'G-NX64GJ20DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAklX6vuohq16V0wFTLIL1R_yW4hbLwNrY',
    appId: '1:951730653228:android:ecb112e042f552825aa989',
    messagingSenderId: '951730653228',
    projectId: 'e-nudge',
    storageBucket: 'e-nudge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPrheVjQ-m0yerPS5FGAmNCeM4GBUJ7Gc',
    appId: '1:951730653228:ios:f44a43fbcd6010ea5aa989',
    messagingSenderId: '951730653228',
    projectId: 'e-nudge',
    storageBucket: 'e-nudge.firebasestorage.app',
    iosClientId: '951730653228-4qgh9b5a0jngscebnsemflaq7lsmaqoo.apps.googleusercontent.com',
    iosBundleId: 'com.sharedreminder.sharedReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPrheVjQ-m0yerPS5FGAmNCeM4GBUJ7Gc',
    appId: '1:951730653228:ios:f44a43fbcd6010ea5aa989',
    messagingSenderId: '951730653228',
    projectId: 'e-nudge',
    storageBucket: 'e-nudge.firebasestorage.app',
    iosClientId: '951730653228-4qgh9b5a0jngscebnsemflaq7lsmaqoo.apps.googleusercontent.com',
    iosBundleId: 'com.sharedreminder.sharedReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0f0NvkYbt2MddVG_oF_UNoJ_AxPRMeAU',
    appId: '1:951730653228:web:f15c612f7ec8f34f5aa989',
    messagingSenderId: '951730653228',
    projectId: 'e-nudge',
    authDomain: 'e-nudge.firebaseapp.com',
    storageBucket: 'e-nudge.firebasestorage.app',
    measurementId: 'G-PCBZYMX1YE',
  );
}
